version: "3"
services:
  broker:
    build: broker
    container_name: broker
    volumes:
      - ./broker/config:/mosquitto/config
      - ./broker/data:/mosquitto/data
      - ./broker/log:/mosquitto/log
    environment:
      - LC_ALL=${LANG}
      - LANG=${LANG}
      - VIRTUAL_PORT=${BROKER_PORT}
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - "${BROKER_HOST}:${BROKER_PORT}:${BROKER_PORT}"
  client:
    build: client
    container_name: client
    volumes:
      - ./client:/app
      - ../libs/python:/libs
    environment:
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
      - BROKER_HOST=broker
      - BROKER_PORT=${BROKER_PORT}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_USER=${CLIENT_USER}
      - CLIENT_PASSWORD=${CLIENT_PASSWORD}
      - LC_ALL=${LANG}
      - LANG=${LANG}
      - PYTHONUNBUFFERED=1
    links:
      - broker
