version: "3"
services:
  broker:
    build: broker
    container_name: broker
    volumes:
      - ./broker/config:/mosquitto/config
      - ./broker/data:/mosquitto/data
      - ./broker/log:/mosquitto/log
    environment:
      - LC_ALL=${LANG}
      - LANG=${LANG}
      - VIRTUAL_PORT=${BROKER_PORT}
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - "${BROKER_HOST}:${BROKER_PORT}:${BROKER_PORT}"
    links:
      - broker_cache
  broker_cache:
    build: cache
    container_name: broker_cache
    environment:
      - LC_ALL=${LANG}
      - LANG=${LANG}
      - CACHE_PASSWORD=${CACHE_PASSWORD}
      - VIRTUAL_PORT=${CACHE_PORT}
    ports:
      - "127.0.0.1:${BROKER_PORT}:${BROKER_PORT}"
    volumes:
      - ./cache/data:/data
  broker_client:
    build: client
    container_name: broker_client
    volumes:
      - ./client:/app
      - ../libs/python:/libs
    environment:
      - BROKER_HOST=broker
      - BROKER_PORT=${BROKER_PORT}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_USER=${CLIENT_USER}
      - CLIENT_PASSWORD=${CLIENT_PASSWORD}
      - DEVICES_HOST=${DEVICES_HOST}
      - DEVICES_PORT=${DEVICES_PORT}
      - LC_ALL=${LANG}
      - LANG=${LANG}
      - PYTHONUNBUFFERED=1
    links:
      - broker
