version: "3"
services:
  message_broker:
    build: message_broker
    container_name: message_broker
    volumes:
      - ./message_broker/config:/mosquitto/config
      - ./message_broker/data:/mosquitto/data
      - ./message_broker/log:/mosquitto/log
    environment:
      - LC_ALL=${LANG}
      - LANG=${LANG}
      - VIRTUAL_PORT=${BROKER_PORT}
    ports:
      - "${BROKER_HOST}:${BROKER_PORT}:${BROKER_PORT}"
